"""Loans tablosu eklendi

Revision ID: 0cdc3dd2f894
Revises: 4fd85008d7c7
Create Date: 2025-12-14 22:55:20.233815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdc3dd2f894'
down_revision = '4fd85008d7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('alis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('son_teslim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('iade_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    # ### end Alembic commands ###
