"""Books tablosu eklendi

Revision ID: 4fd85008d7c7
Revises: 350b24ca62f4
Create Date: 2025-12-14 22:08:44.841135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd85008d7c7'
down_revision = '350b24ca62f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=150), nullable=False),
    sa.Column('yazar', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
